theme = "monokai_pro_machine"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
h = "move_next_word_end"
H = "move_next_long_word_end"
k = "search_next"
K = "search_prev"
l = "insert_mode"
L = "insert_at_line_start"
E = "open_below"
I = "open_above"

# C-s = ":w"
# C-o = ":open ~/.config/helix/config.toml"
C-d = ["search_selection", "extend_search_next"]
C-r = [":w", ":config-reload"]

[keys.normal.g]
k = "no_op"
j = "no_op"
h = "no_op"
l = "no_op"
n = "goto_line_start"
o = "goto_line_end"


[keys.select]
n = "extend_char_left"
e = "extend_line_down"
i = "extend_line_up"
o = "extend_char_right"
h = "extend_next_word_end"
H = "extend_next_long_word_end"
k = "extend_search_next"
K = "extend_search_prev"
l = "insert_mode"
L = "insert_at_line_start"
E = "open_below"
I = "open_above"
C-d = ["search_selection", "extend_search_next"]

# view mode
[keys.normal.z]
e = "scroll_down"
i = "scroll_up"
# sticky view mode
[keys.normal.Z]
e = "scroll_down"
i = "scroll_up"

[keys.normal.space]
q = "move_line_down"

[keys.normal."C-w"]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
C-h = "no_op"
C-j = "no_op"
C-k = "no_op"
C-l = "no_op"

n = "jump_view_left"
e = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
C-n = "jump_view_left"
C-e = "jump_view_down"
C-i = "jump_view_up"
C-o = "jump_view_right"

N = "swap_view_left"
E = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"

m = "wonly" # Like "me"
